### ISSUE TITLE
test failures on latest version

### ISSUE THREAD

**Issue by barisusakli** [socketio/socket.io-parser#123]
```
$ npm ls socket.io-parser
nodebb@3.1.4 D:\github\NodeBB
├─┬ socket.io-client@4.6.1
│ └── socket.io-parser@4.2.3
└─┬ socket.io@4.6.1
  └── socket.io-parser@4.2.3 deduped
````

Getting below error on version 4.2.3, was fine on 4.2.1

```
.Missing error handler on `socket`.
Error: invalid payload
    at Decoder.decodeString (D:\github\NodeBB\node_modules\socket.io-parser\build\cjs\index.js:223:23)
    at Decoder.add (D:\github\NodeBB\node_modules\socket.io-parser\build\cjs\index.js:126:27)        
    at Client.ondata (D:\github\NodeBB\node_modules\socket.io\dist\client.js:182:26)
    at Socket.emit (node:events:513:28)
    at Socket.onPacket (D:\github\NodeBB\node_modules\engine.io\build\socket.js:116:22)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.onPacket (D:\github\NodeBB\node_modules\engine.io\build\transport.js:92:14)
    at WebSocket.onData (D:\github\NodeBB\node_modules\engine.io\build\transport.js:101:14)
    at WebSocket.<anonymous> (D:\github\NodeBB\node_modules\engine.io\build\transports\websocket.js:20:19)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (D:\github\NodeBB\node_modules\engine.io\node_modules\ws\lib\websocket.js:1178:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (D:\github\NodeBB\node_modules\engine.io\node_modules\ws\lib\receiver.js:528:14)
    at Receiver.getData (D:\github\NodeBB\node_modules\engine.io\node_modules\ws\lib\receiver.js:446:17)
    at Receiver.startLoop (D:\github\NodeBB\node_modules\engine.io\node_modules\ws\lib\receiver.js:148:22)
    at Receiver._write (D:\github\NodeBB\node_modules\engine.io\node_modules\ws\lib\receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.socketOnData (D:\github\NodeBB\node_modules\engine.io\node_modules\ws\lib\websocket.js:1272:35)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by darrachequesne** [comment]
Hi! This might be linked to https://github.com/socketio/socket.io-parser/commit/3b78117bf6ba7e99d7a5cfc1ba54d0477554a7f3, I'm digging into this.

**Comment by darrachequesne** [comment]
Could you please provide some instructions to run the tests in your repository?

I tried to follow the instructions there: https://docs.nodebb.org/development/#testing

Here's my `config.json`:

```json
{
  "url": "http://127.0.0.1:4567",
  "secret": "abc123",
  "test_database": {
    "host": "127.0.0.1",
    "port": "27017",
    "username": "",
    "password": "",
    "database": "mongo"
  }
}
```

And then:

```
$ npm test

> nodebb@3.1.4 test
> nyc --reporter=html --reporter=text-summary mocha

info: configJSON
info: {
  "url": "http://127.0.0.1:4567",
  "secret": "abc123",
  "test_database": {
        "host": "127.0.0.1",
        "port": "27017",
        "username": "",
        "password": "",
        "database": "mongo"
  }
}
info: database config undefined {"database":"mongo","host":"127.0.0.1","password":"","port":"27017","username":""}
info: environment production

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.<anonymous> (/git/socket.io/NodeBB/src/topics/posts.js:2:688)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.replacementCompile (/git/socket.io/NodeBB/node_modules/append-transform/index.js:60:13)
```

I must have missed some steps?

**Comment by barisusakli** [comment]
You can use a config.json like below.

```
{
    "url": "http://127.0.0.1:4567",
    "secret": "abc",
    "database": "mongo",
    "port": "4567",
    "mongo": {
        "host": "127.0.0.1",
        "port": "27017",
        "password": "",
        "database": "baris_dev",
        "uri": "mongodb://127.0.0.1:27017/baris_dev"
    },
    "test_database": {
        "host": "127.0.0.1",
        "port": "27017",
        "password": "",
        "database": "test_db"
    }   
}
```

Let me know if that works.

**Comment by darrachequesne** [comment]
Thanks for the tip :+1: 

I was able to run the tests. It seems you are sending an array as the event name there: https://github.com/NodeBB/NodeBB/blob/82e26829c5d4fadde705b854ef1a8f37c22ffd23/test/socket.io.js#L110-L116

Due to https://github.com/socketio/socket.io-parser/commit/3b78117bf6ba7e99d7a5cfc1ba54d0477554a7f3, the packet is now discarded and the connection is closed, as the event name is not a `string` nor a `number`. What do you think?

**Comment by barisusakli** [comment]
@darrachequesne sounds good, I can remove our test if those messages are discarded by socket.io now.
