### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kevgathuku** [socketio/socket.io-parser#63]
Hello, I keep getting this error when using the socket.io server.
It seems to be raised when I call the `socket.emit` function.
```
/app/node_modules/socket.io-parser/binary.js:99
 function _removeBlobs(obj, curKey, containingObject) {
                      ^
RangeError: Maximum call stack size exceeded
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:99:24)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:126:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:126:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)
   at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:126:9)
```

**Comment by darrachequesne** [comment]
@kevgathuku are you trying to send a recursive object? or only a big json object?

**Comment by kevgathuku** [comment]
Hey @darrachequesne,
First, thanks for taking your time to reply.
I figured it out. It seems I was mistakenly trying to send an object that contained files in one of the fields 🙈 so this was happening when trying to parse the file(s).
I resorted to removing the files and sending out their attributes instead, e.g. file name, size, etc.
I'll go ahead and close this as it was a mistake on my part.
