### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by ORESoftware** [socketio/socket.io-parser#72]
I am seeing this error:
```console

 Error: Cannot find module 'has-binary2'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/oleg/WebstormProjects/oresoftware/sumanjs/suman/node_modules/socket.io-parser/index.js:8:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3) 
```

I think it's coming from this lib

**Comment by darrachequesne** [comment]
@ORESoftware `has-binary2` is listed as dependency ([^](https://github.com/socketio/socket.io-parser/blob/3.1.2/package.json#L17)), so that should work. Did you try to run `npm i`?

**Comment by antony** [comment]
Strange, I get the same error when modules which use `engine.io-parser` (a dependency of this library) are installed via `lerna`.

I'll look at the `engine.io-parser` to see if the dependency is missing there.
